### ISSUE TITLE
are 'if' an expression ?

### ISSUE THREAD

**Issue by nanjizal** [anissen/cosy#6]
print if b < 5 and 4 == 4 {
    'true'
} else {
    'false'
}
I wondered because I was thinking about expression blocks in haxe and needing a blockReturn and wondered

**Comment by anissen** [comment]
Hi @nanjizal! 

No, not yet at least! `if`'s are [statements](https://github.com/anissen/cosy/blob/main/src/cosy/Stmt.hx#L14).

However, I am [considering](https://github.com/anissen/cosy/blob/main/wishlist.md?plain=1#L14) making more statements into expressions. 

I am not sure what you mean by a "blockReturn" -- can you explain?

**Comment by nanjizal** [comment]
I wrote this possible proposal but Rudy did not seem keen, he felt that Rust has something like this and it represented vailed goto's.
Notbilly felt I needed to pose the proposal more in terms of industry standards, perhaps in reference to one or more other languages, but seemed interested in the problem sphere and it seemed a valid possibility.
Cosy maybe ideal for testing such concepts without Ocaml complexity.
https://github.com/nanjizal/haxe-evolution/blob/master/proposals/0000-early-block.md
at the moment I am unsure if it is worth putting to evolution, I think the concept could be powerful but uncertain around proposal of the concept.

**Comment by nanjizal** [comment]
cosy looks interesting, I am just unsure on when it would be better over just using haxe.. maybe for learning dev. I know luxe engine was moved to wren for simple language aspects.

**Comment by anissen** [comment]
Thanks for sharing your thoughts, it's definitely an interesting idea and nothing I had considered myself.
I don't actually check if `break` or `continue` are used inside their intended contexts, which means that the following will be validated and run.
```
{
    print '1'
    if (1 < 3) break
    if (1 < 3) continue
    print '2'
}
```
However fail at runtime because I don't handle that case ;)
It should be trivial to handle though. I need to consider further if this is something that I _want_ to support. Also, I would probably need for more statements to be expressions (e.g. `if`) for something like this to be valuable.
